language: python

os:
  - linux

sudo: false

cache: pip

python:
  - "3.5"

script:
  - 'python setup.py test --tox-args="-e$TOX_ENV"'

env:
  - TOX_ENV=py27
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=docs
